# Generated by Django 3.0.2 on 2020-01-25 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20200125_1229'),
        ('org', '0003_auto_20200125_1229'),
        ('process', '0002_auto_20200125_1229'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_jobs', to='org.Department'),
        ),
        migrations.AlterField(
            model_name='job',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_jobs', to='process.Node'),
        ),
        migrations.AlterField(
            model_name='job',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_jobs', to='org.Organization'),
        ),
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_jobs', to='people.Role'),
        ),
        migrations.AlterField(
            model_name='job',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_jobs', to='planning.Shift'),
        ),
        migrations.AlterField(
            model_name='job',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_jobs', to='people.Worker'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_shifts', to='org.Department'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_shifts', to='org.Organization'),
        ),
    ]
