# Generated by Django 3.0.2 on 2020-01-22 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
        ('people', '0002_manager_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='org.Organization'),
        ),
    ]
