# Generated by Django 3.0.2 on 2020-01-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_manager_darkmodeenabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='darkModeEnabled',
            new_name='dark_mode_enabled',
        ),
    ]
