# Generated by Django 3.0.2 on 2020-01-25 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_organization_code'),
        ('people', '0005_auto_20200124_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_managers', to='org.Department'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_managers', to='org.Organization'),
        ),
    ]
