# Generated by Django 3.0.2 on 2020-01-25 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_auto_20200125_1229'),
        ('people', '0006_auto_20200125_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_roles', to='org.Department'),
        ),
        migrations.AlterField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_roles', to='org.Organization'),
        ),
        migrations.AlterField(
            model_name='role',
            name='workers',
            field=models.ManyToManyField(related_name='worker_roles', to='people.Worker'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_workers', to='org.Cohort'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_workers', to='org.Department'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_workers', to='org.Organization'),
        ),
    ]
