# Generated by Django 3.0.2 on 2020-01-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20200125_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=50),
        ),
    ]
