# Generated by Django 3.0.2 on 2020-01-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20200129_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='preferred_workspace_key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
