# Generated by Django 3.0.2 on 2020-01-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_worker_preferred_workspace_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='preferred_workspace_key',
        ),
        migrations.AddField(
            model_name='manager',
            name='preferred_workspace_key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
