# Generated by Django 3.0.2 on 2020-02-05 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SVGElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_shape', models.CharField(max_length=50, null=True)),
                ('svg_stroke', models.IntegerField(null=True)),
                ('svg_stroke_width', models.IntegerField(null=True)),
                ('svg_m', models.IntegerField(null=True)),
                ('svg_l', models.IntegerField(null=True)),
                ('svg_points', models.CharField(max_length=50, null=True)),
                ('svg_x', models.IntegerField(null=True)),
                ('svg_y', models.IntegerField(null=True)),
                ('svg_height', models.IntegerField(null=True)),
                ('svg_width', models.IntegerField(null=True)),
                ('svg_fill_r', models.IntegerField(null=True)),
                ('svg_fill_g', models.IntegerField(null=True)),
                ('svg_fill_b', models.IntegerField(null=True)),
                ('svg_opacity', models.FloatField(default=1.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_workspaces', to='org.Department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_workspaces', to='org.Organization')),
                ('svg', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='process.SVGElement')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('x', models.IntegerField(default=100)),
                ('y', models.IntegerField(default=100)),
                ('z', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=500)),
                ('width', models.IntegerField(default=500)),
                ('color', models.CharField(default='#FFFFFF', max_length=50)),
                ('draggable', models.BooleanField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_zones', to='org.Department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_zones', to='org.Organization')),
                ('svg', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='process.SVGElement')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_zones', to='process.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('volume', models.IntegerField(null=True)),
                ('x', models.IntegerField(default=100)),
                ('y', models.IntegerField(default=100)),
                ('height', models.IntegerField(default=104)),
                ('width', models.IntegerField(default=300)),
                ('color', models.CharField(default='#FFFFFF', max_length=50)),
                ('draggable', models.BooleanField(default=1)),
                ('is_active', models.BooleanField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_nodes', to='org.Department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_nodes', to='org.Organization')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_nodes', to='people.Role')),
                ('svg', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='process.SVGElement')),
                ('worker', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_node', to='people.Worker')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_nodes', to='process.Workspace')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_nodes', to='process.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='FlowpathZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_zone_flows', to='org.Department')),
                ('input_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_ins', to='process.Zone')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_zone_flows', to='org.Organization')),
                ('output_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_outs', to='process.Zone')),
                ('svg', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='process.SVGElement')),
            ],
        ),
        migrations.CreateModel(
            name='FlowpathWorkspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('input_workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_ins', to='process.Workspace')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_workspace_flows', to='org.Organization')),
                ('output_workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_outs', to='process.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='FlowpathNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_node_flows', to='org.Department')),
                ('input_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_ins', to='process.Node')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_node_flows', to='org.Organization')),
                ('output_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_outs', to='process.Node')),
                ('svg', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='process.SVGElement')),
            ],
        ),
    ]
