# Generated by Django 3.0.2 on 2020-01-18 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SVGElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_shape', models.CharField(max_length=50, null=True)),
                ('svg_stroke', models.IntegerField(null=True)),
                ('svg_stroke_width', models.IntegerField(null=True)),
                ('svg_m', models.IntegerField(null=True)),
                ('svg_l', models.IntegerField(null=True)),
                ('svg_points', models.CharField(max_length=50, null=True)),
                ('svg_x', models.IntegerField(null=True)),
                ('svg_y', models.IntegerField(null=True)),
                ('svg_height', models.IntegerField(null=True)),
                ('svg_width', models.IntegerField(null=True)),
                ('svg_fill_r', models.IntegerField(null=True)),
                ('svg_fill_g', models.IntegerField(null=True)),
                ('svg_fill_b', models.IntegerField(null=True)),
                ('svg_opacity', models.FloatField(default=1.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.Department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Organization')),
                ('svg', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='process.SVGElement')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.Department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Organization')),
                ('svg', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='process.SVGElement')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('volume', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.Department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Organization')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Role')),
                ('svg', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='process.SVGElement')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Workspace')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='FlowpathZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Department')),
                ('input_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowpath_in', to='process.Zone')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Organization')),
                ('output_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowpath_out', to='process.Zone')),
                ('svg', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='process.SVGElement')),
            ],
        ),
        migrations.CreateModel(
            name='FlowpathWorkspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('input_workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowpath_in', to='process.Workspace')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Organization')),
                ('output_workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowpath_out', to='process.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='FlowpathNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Department')),
                ('input_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowpath_in', to='process.Node')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Organization')),
                ('output_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowpath_out', to='process.Node')),
                ('svg', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='process.SVGElement')),
            ],
        ),
    ]
