# Generated by Django 3.0.2 on 2020-01-25 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20200125_1229'),
        ('org', '0003_auto_20200125_1229'),
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowpathnode',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_node_flows', to='org.Department'),
        ),
        migrations.AlterField(
            model_name='flowpathnode',
            name='input_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_ins', to='process.Node'),
        ),
        migrations.AlterField(
            model_name='flowpathnode',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_node_flows', to='org.Organization'),
        ),
        migrations.AlterField(
            model_name='flowpathnode',
            name='output_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_outs', to='process.Node'),
        ),
        migrations.AlterField(
            model_name='flowpathworkspace',
            name='input_workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_ins', to='process.Workspace'),
        ),
        migrations.AlterField(
            model_name='flowpathworkspace',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_workspace_flows', to='org.Organization'),
        ),
        migrations.AlterField(
            model_name='flowpathworkspace',
            name='output_workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_outs', to='process.Workspace'),
        ),
        migrations.AlterField(
            model_name='flowpathzone',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_zone_flows', to='org.Department'),
        ),
        migrations.AlterField(
            model_name='flowpathzone',
            name='input_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_ins', to='process.Zone'),
        ),
        migrations.AlterField(
            model_name='flowpathzone',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_zone_flows', to='org.Organization'),
        ),
        migrations.AlterField(
            model_name='flowpathzone',
            name='output_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_outs', to='process.Zone'),
        ),
        migrations.AlterField(
            model_name='node',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_nodes', to='org.Department'),
        ),
        migrations.AlterField(
            model_name='node',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_nodes', to='org.Organization'),
        ),
        migrations.AlterField(
            model_name='node',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_nodes', to='people.Role'),
        ),
        migrations.AlterField(
            model_name='node',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_nodes', to='process.Workspace'),
        ),
        migrations.AlterField(
            model_name='node',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_nodes', to='process.Zone'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_workspaces', to='org.Department'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_workspaces', to='org.Organization'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_zones', to='org.Department'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_zones', to='org.Organization'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_zones', to='process.Workspace'),
        ),
    ]
