# Generated by Django 3.0.2 on 2020-01-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_auto_20200128_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='height',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='node',
            name='width',
            field=models.IntegerField(default=300),
        ),
    ]
