# Generated by Django 3.0.2 on 2020-01-29 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_role_color'),
        ('process', '0005_node_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='worker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_worker', to='people.Worker'),
        ),
    ]
