# Generated by Django 3.0.2 on 2020-01-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_auto_20200128_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='draggable',
            field=models.BooleanField(default=True),
        ),
    ]
