# Generated by Django 3.0.2 on 2020-01-29 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_node_draggable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_nodes', to='process.Zone'),
        ),
    ]
