# Generated by Django 3.0.2 on 2020-01-30 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_auto_20200130_1103'),
        ('process', '0008_auto_20200129_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='worker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_node', to='people.Worker'),
        ),
    ]
