# Generated by Django 3.0.2 on 2020-02-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0009_auto_20200130_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='height',
            field=models.IntegerField(default=104),
        ),
    ]
