# Generated by Django 3.0.2 on 2020-02-04 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_cohort_is_active'),
        ('process', '0010_auto_20200203_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='z',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zone',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_zones', to='org.Department'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='svg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='process.SVGElement'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_zones', to='process.Workspace'),
        ),
    ]
