# Generated by Django 3.0.2 on 2020-02-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0011_auto_20200204_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='zone',
            name='draggable',
            field=models.BooleanField(default=1),
        ),
    ]
