# Generated by Django 3.0.2 on 2020-01-25 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_organization_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_cohorts', to='org.Organization'),
        ),
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_departments', to='org.Organization'),
        ),
    ]
