# Generated by Django 3.0.2 on 2020-01-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_auto_20200125_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cohort',
            old_name='code',
            new_name='name',
        ),
    ]
