# Generated by Django 3.0.2 on 2020-01-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_auto_20200125_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=50),
        ),
        migrations.AddField(
            model_name='department',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=50),
        ),
    ]
