# Generated by Django 3.0.2 on 2020-01-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='full_name',
            field=models.CharField(max_length=180, null=True),
        ),
    ]
